### ISSUE TITLE
Analyzing frequency of word occurence does not ignore case

### ISSUE THREAD

**Issue by maximumdata** [maximumdata/markov-generator#1]
The analysis function does not ignore case, resulting in output that will be an exact copy of the input in the case that it is passed an array similar to:

`['This is a sample', 'THIS IS ALSO A SAMPLE', 'this Is yet ANOTHER sample']`

If `'THIS'` is selected as the starting word, the only possible outcome currently will be the full string of input `'THIS IS ALSO A SAMPLE'`.

The constructor function needs to be refactored to convert all strings to lowercase during analysis, while ideally not storing the converted string. Given the above sample array, this would allow a potential output to be `'THIS Is a SAMPLE'`.

**Comment by mmlanders23** [comment]
Hey @maximumdata. I'd like to contribute. Is there any documentation as to how I might do so?

**Comment by maximumdata** [comment]
Hey @mmlanders23! I'm happy for the help. There isn't currently a CONTRIBUTING.md, but there will be soon. For now though, all you should need is node (v6 at least), and a fork of this repo. The code relating to this issue would need to take place in the constructor function of the Markov class, found in index.js. To test it out, you could follow the example in the Quickstart section of the readme, however later today I will include a test setup in this repo itself.

**Comment by mmlanders23** [comment]
Hey @maximumdata. Sorry for the brief delay in updating that PR, my schedule filled up with holiday travels and obligations. Will work on getting that to you ASAP.
